version: '3'
services:
  db:
    build: db/postgres
    env_file: 
      - db/postgres/env_vars.env

  web:
    build: .
    command: >
      bash -c "sleep 4 && 
      bundle exec rake db:create &&
      bundle exec rake db:migrate &&
      rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:80"
    depends_on:
      - db

  client:
    build: client
    depends_on:
      - web
    links:
      - web
    ports:
      - "${WEB_PORT}:80"
    environment:
      - "API_HOST=${HOST}:${API_PORT}"
